# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-11 03:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import django_contentdb.utils


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_contentdb", "0001_initial"),
        ("django_contentdb", "0002_contenttypepermission_created_at_and_more"),
        ("django_contentdb", "0003_alter_draft_options_alter_image_options_and_more"),
        ("django_contentdb", "0004_language_name_en_language_name_pl_contentchannel_and_more"),
        ("django_contentdb", "0005_contenttype_supports_authors_author_draftauthor_and_more"),
        ("django_contentdb", "0006_author_uid_unique_is_active_index"),
        ("django_contentdb", "0007_draft_is_system"),
    ]

    # Data ops from the old chain intentionally not carried over:
    # 0005 set_blog_post_supports_authors backfilled rows that cannot exist on a fresh
    # database (ContentType table is empty at install time) — a no-op here.

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRights",
            fields=[
                ("access_level", models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttributeSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(editable=False, max_length=64)),
                ("label", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=256)),
                ("slug", models.SlugField(max_length=256, unique=True)),
                ("role_t9n", models.JSONField(blank=True, default=dict)),
                ("description_t9n", models.JSONField(blank=True, default=dict)),
                ("tag_t9n", models.JSONField(blank=True, default=dict)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=256)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=64)),
                ("contact_url", models.URLField(blank=True, default="", max_length=512)),
                ("social_profiles", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=256)),
                ("url_key", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ContentChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ContentSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "image",
                    django_contentdb.utils.HashedImageField(
                        editable=False,
                        height_field="height",
                        storage=django_contentdb.utils.UniqueFileSystemStorage(),
                        upload_to="image",
                        width_field="width",
                    ),
                ),
                ("width", models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ("height", models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("publish", "Publish"),
                            ("view", "View"),
                        ],
                        max_length=12,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(editable=False, max_length=64)),
                ("label", models.CharField(max_length=64)),
                ("is_bool", models.BooleanField(default=False)),
                ("is_int", models.BooleanField(default=False)),
                ("is_txt", models.BooleanField(default=False)),
                ("is_txt_t9n", models.BooleanField(default=False)),
                ("is_txt_long", models.BooleanField(default=False)),
                ("is_datetime", models.BooleanField(default=False)),
                ("is_filterable", models.BooleanField(default=False)),
                ("is_searchable", models.BooleanField(default=False)),
                ("is_comparable", models.BooleanField(default=False)),
                ("allow_new_values", models.BooleanField(default=True)),
                ("allow_many_values", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("slug",), name="attribute_slug_is_unique")],
            },
        ),
        migrations.CreateModel(
            name="AttributeToSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attribute",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.attribute"),
                ),
                (
                    "attribute_set",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.attributeset"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attributeset",
            name="attributes",
            field=models.ManyToManyField(
                related_name="attribute_sets",
                through="django_contentdb.AttributeToSet",
                to="django_contentdb.attribute",
            ),
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                ("value_txt", models.CharField(blank=True, max_length=128, null=True)),
                ("value_txt_t9n", models.JSONField(blank=True, null=True)),
                ("value_txt_long", models.CharField(blank=True, max_length=2048, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="django_contentdb.attribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("content", models.JSONField(default=dict)),
                ("extension", models.JSONField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_contentdb.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.attributevalue"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.content"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="attributes",
            field=models.ManyToManyField(
                related_name="content_set",
                through="django_contentdb.ContentAttribute",
                to="django_contentdb.attributevalue",
            ),
        ),
        migrations.CreateModel(
            name="ContentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_layout_extender", models.BooleanField(default=False)),
                ("supports_authors", models.BooleanField(default=False)),
                (
                    "attribute_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_types",
                        to="django_contentdb.attributeset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentTypePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("publish", "Publish"),
                            ("view", "View"),
                        ],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="django_contentdb.contenttype",
                    ),
                ),
                ("group", models.ManyToManyField(blank=True, to="auth.group")),
                ("user", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Deleted",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.content"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_rights",
                    models.ManyToManyField(related_name="draft_access", to="django_contentdb.accessrights"),
                ),
                (
                    "channels",
                    models.ManyToManyField(blank=True, related_name="drafts", to="django_contentdb.contentchannel"),
                ),
                (
                    "content",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.content"),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.contenttype"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DraftAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_author_links",
                        to="django_contentdb.author",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_authors",
                        to="django_contentdb.draft",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="draft",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="drafted_as_author",
                through="django_contentdb.DraftAuthor",
                to="django_contentdb.author",
            ),
        ),
        migrations.CreateModel(
            name="DraftCoAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_co_author_links",
                        to="django_contentdb.author",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_co_authors",
                        to="django_contentdb.draft",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="draft",
            name="co_authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="drafted_as_co_author",
                through="django_contentdb.DraftCoAuthor",
                to="django_contentdb.author",
            ),
        ),
        migrations.CreateModel(
            name="DraftToContentSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_set",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.contentset"),
                ),
                ("draft", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.draft")),
            ],
        ),
        migrations.AddField(
            model_name="contentset",
            name="members",
            field=models.ManyToManyField(through="django_contentdb.DraftToContentSet", to="django_contentdb.draft"),
        ),
        migrations.AddField(
            model_name="author",
            name="photo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_contentdb.image"
            ),
        ),
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=64)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("slug",), name="unique_slug")],
            },
        ),
        migrations.CreateModel(
            name="ImageToTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.image")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.imagetag")),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(through="django_contentdb.ImageToTag", to="django_contentdb.imagetag"),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("iso3", models.CharField(max_length=3)),
                ("iso2", models.CharField(max_length=2)),
                ("name_en", models.CharField(blank=True, default="", max_length=64)),
                ("name_pl", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("iso2",), name="unique_iso2_per_language"),
                    models.UniqueConstraint(fields=("iso3",), name="unique_iso3_per_language"),
                ],
            },
        ),
        migrations.AddField(
            model_name="draft",
            name="language",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.language"
            ),
        ),
        migrations.AddField(
            model_name="contentchannel",
            name="default_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_channels",
                to="django_contentdb.language",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="language",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_contentdb.language"
            ),
        ),
        migrations.CreateModel(
            name="Published",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="django_contentdb.content"),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published",
                        to="django_contentdb.draft",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=256)),
                ("label", models.CharField(blank=True, default="", max_length=256)),
                (
                    "placement",
                    models.CharField(choices=[("top", "Top"), ("bottom", "Bottom")], default="top", max_length=12),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("drafts", models.ManyToManyField(related_name="routes", to="django_contentdb.draft")),
            ],
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("method", models.CharField(choices=[("optimize", "Optimize")], editable=False, max_length=32)),
                (
                    "image",
                    django_contentdb.utils.HashedImageField(
                        editable=False,
                        height_field="height",
                        storage=django_contentdb.utils.UniqueFileSystemStorage(),
                        upload_to="thumb",
                        width_field="width",
                    ),
                ),
                ("width", models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ("height", models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="django_contentdb.image",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="attributeset",
            constraint=models.UniqueConstraint(fields=("slug",), name="attribute_set_slug_is_unique"),
        ),
        migrations.AddConstraint(
            model_name="contenttype",
            constraint=models.UniqueConstraint(fields=("slug",), name="content_type_slug_is_unique"),
        ),
        migrations.AddConstraint(
            model_name="contenttypepermission",
            constraint=models.UniqueConstraint(
                fields=("action", "content_type"), name="unique_action_per_type_per_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="draftauthor",
            constraint=models.UniqueConstraint(fields=("draft", "author"), name="unique_author_per_draft"),
        ),
        migrations.AddConstraint(
            model_name="draftcoauthor",
            constraint=models.UniqueConstraint(fields=("draft", "author"), name="unique_co_author_per_draft"),
        ),
        migrations.AddConstraint(
            model_name="drafttocontentset",
            constraint=models.UniqueConstraint(fields=("draft",), name="draft_unique_per_table"),
        ),
        migrations.AddConstraint(
            model_name="imagetotag",
            constraint=models.UniqueConstraint(fields=("image", "tag"), name="unique_tag_per_image"),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(fields=("url",), name="route_is_unique"),
        ),
        migrations.AddConstraint(
            model_name="thumbnail",
            constraint=models.UniqueConstraint(
                fields=("method", "source", "width", "height"), name="unique_thumbnail_per_source_per_method_per_size"
            ),
        ),
    ]
